GET http://localhost:3212/placetype

###
GET http://localhost:3212/placetype/

###
POST http://localhost:3212/placetype
Content-Type: application/json

{
    "typeName" : "mini market"
}

###
PUT  http://localhost:3212/placetype/
Content-Type: application/json

{
    "name": "Kristen"
}

###
DELETE http://localhost:3212/placetype/
