GET http://localhost:3000/placetype

###
GET http://localhost:3000/placetype/

###
POST http://localhost:3000/placetype
Content-Type: application/json

{
    "username": "Petir",
    "email": "petir@gmail.com",
    "religionId": "9687a322-c6b9-4ea5-9ff7-b7cbc543d1b3"
}

###
PUT  http://localhost:3000/placetype/
Content-Type: application/json

{
    "name": "Kristen"
}

###
DELETE http://localhost:3000/placetype/
